export const CREATE_PESSOA = "CREATE_PESSOA";
export const RETRIEVE_PESSOA = "RETRIEVE_PESSOA";
export const UPDATE_PESSOA = "UPDATE_PESSOA";
export const DELETE_PESSOA = "DELETE_PESSOA";
export const DELETE_ALL_PESSOA = "DELETE_ALL_PESSOA";

export const RETRIEVE_CEP = "RETRIEVE_CEP";
export const RETRIEVE_ALL_CEP = "RETRIEVE_ALL_CEP";